# Generated by Django 5.0.1 on 2024-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='audio',
            field=models.FileField(default='', upload_to='audio/'),
            preserve_default=False,
        ),
    ]
